#!/bin/bash
port=45000
windowsize=8
error=0
serverIP=127.0.0.1
filename=file1
kill -9 $(lsof -i udp:$port | tail -1 | awk '{print $2}')
set -e
make
mv client test
./server $port $windowsize $error &
cd test
./client $serverIP $port $filename
cat $filename
cd ..
