#!/bin/bash
port=45000
windowsize=8
error=0
serverIP=127.0.0.1
filename=file1
./kill-server $port
set -e
make
mv client test
./server $port $windowsize $error &
cd test
./client $serverIP $port $filename
cat $filename
cd ..
