#!/bin/bash
port=45000
windowsize=$1
error=$2
serverIP=127.0.0.1
filename=$3
./kill-server $port
make >&/dev/null
mv client test
./server $port $windowsize $error &
cd test
rm $filename
echo exit | time ./client $serverIP $port $filename
cat $filename
cd ..
